### PR TITLE
Update main.cpp (string to int conversion)

### PR DESCRIPTION
**Pull request by jverploeg**
When I tried to compile, i got an error with your string to integer conversion.  You need to include stdlib.h for the conversion, and use atoi rather than stoi.  I'm not sure what additional libraries you need when using stoi, but possibly the syntax is just incorrect. 
When using atoi, you cant just say 

int x;
string y;
x=atoi(y);

you need to say
x=atoi(y.c_str());

### CODE REVIEW

**Comment by KianTanner** [comment]
They did include stdlib.h, it just needs to be compiled with c++ 11, which they should make a note of in the readme. Using atoi is a viable soloution as well, however.

**Comment by KianTanner** [comment]
The stdlib.h is included in DecisionTree.h, by the way.

**Comment by jverploeg** [comment]
My mistake, I did not notice it in the header file.  Thanks for pointing that out.

**Comment by lawalton** [comment]
Thanks for the input, my apologies about not including the note in the readme file. It's probably best to just use jverploeg's suggestion with atoi. Thanks!

**Pull request merged**
